name: Flatpak

on: 
  push:
  workflow_dispatch:
#  push:
#    branches: [main]
#  pull_request:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:kde-6.5
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: xca.flatpak
        manifest-path: misc/de.hohnstaedt.xca.yaml
        cache-key: flatpak-builder-${{ github.sha }}
